import { EntityId } from "@reduxjs/toolkit";

// Generated by https://quicktype.io
type ColorHex = `#${string}`;

export interface PlacesResponse {
	html_attributions: any[];
	next_page_token: string;
	results: PlacesResult[];
	status: string;
}

export interface PlacesResult {
	business_status: BusinessStatus;
	formatted_address: string;
	geometry: Geometry;
	icon: string;
	icon_background_color: ColorHex;
	icon_mask_base_uri: string;
	name: string;
	opening_hours: OpeningHours;
	photos: Photo[];
	place_id: EntityId;
	plus_code: PlusCode;
	price_level?: number;
	rating: number;
	reference: string;
	types: string[];
	user_ratings_total: number;
}

export enum BusinessStatus {
	Operational = "OPERATIONAL",
}

export interface Geometry {
	location: Coordinate;
	viewport: Viewport;
}

export interface Coordinate {
	lat: number;
	lng: number;
}

export interface Viewport {
	northeast: Coordinate;
	southwest: Coordinate;
}

export interface OpeningHours {
	open_now: boolean;
}

export interface Photo {
	height: number;
	html_attributions: string[];
	photo_reference: string;
	width: number;
}

export interface PlusCode {
	compound_code: string;
	global_code: string;
}
